apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: legacy
resources:
  - ../../base
images:
  - name: ghcr.io/sdhayanand/tb-erp-mq-consumer
    newTag: local
patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: erp-mq-consumer
      data:
        JMS_PROVIDER: "artemis"
        JMS_URL: "tcp://ems-broker.legacy.svc.cluster.local:61616"
