apiVersion: v1
kind: Service
metadata:
  name: erp-mq-consumer
  labels:
    app: erp-mq-consumer
spec:
  type: ClusterIP
  selector:
    app: erp-mq-consumer
  ports:
    - name: http
      port: 8087
      targetPort: http
