apiVersion: v1
kind: Service
metadata:
  name: legacy-oms-soap
  labels:
    app: legacy-oms-soap
spec:
  type: ClusterIP
  selector:
    app: legacy-oms-soap
  ports:
    - name: http
      port: 8085
      targetPort: http
