apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: legacy
resources:
  - ../../base
images:
  - name: ghcr.io/sdhayanand/tb-legacy-oms-soap
    newName: us-central1-docker.pkg.dev/PROJECT_ID/tb-otd/legacy-oms-soap
    newTag: latest
patches:
  - path: serviceaccount-patch.yaml
  - path: configmap-patch.yaml
