apiVersion: v1
kind: Service
metadata:
  name: ibm-mq
  labels:
    app: ibm-mq
spec:
  type: ClusterIP
  selector:
    app: ibm-mq
  ports:
    - name: mq
      port: 1414
      targetPort: mq
    - name: console
      port: 9443
      targetPort: console
